### ISSUE TITLE
Document API methods

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.rollups#64]
We need to document the following API methods:

- findMoneyOrderCreation(operationHash)
- findMoneyOrderRedemption(operationHash)
- findOutboundTransfer(operationHash)

See: https://github.com/ConsenSys/sumo/pull/2174

**Comment by alexandratran** [comment]
Also see https://github.com/ConsenSys/sumo/pull/2324, which adds `accountId` to the find operation APIs.

**Comment by rolandtyler** [comment]
Closed to #76
