### ISSUE TITLE
Document updated `transaction_fetch` config option

### ISSUE THREAD

**Issue by alexandratran** [ConsenSys/doc.rollups#77]
Document updated `transaction_fetch` engine configuration option. See https://github.com/ConsenSys/sumo/pull/2522 and check that it is merged first.

**Comment by rolandtyler** [comment]
Feature not needed. Per Jakub Trad:
> Hey, my bad, we have since changed the approach and the documented configuration options will soon be removed. I'll make sure not to use the doc-change-required unless the feature is stabilized
